# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dnh_nbdev_test',
                'doc_host': 'https://danhorner.github.io',
                'git_url': 'https://github.com/danhorner/dnh_nbdev_test',
                'lib_path': 'dnh_nbdev_test'},
  'syms': {'dnh_nbdev_test.core': {'dnh_nbdev_test.core.foo': ('core.html#foo', 'dnh_nbdev_test/core.py')}}}
